### PR TITLE
Fb events integration

### PR DESCRIPTION
**Pull request by maxwell-bland**
Added angular rendering to front-end, a route to grab the facebook events, and an ignore for the .env file which stores the app's secret keys to the API.

### CODE REVIEW

**Comment by jsdavis** [comment]
Can't merge it with failing tests

**Comment by maxwell-bland** [comment]
Hmm, not sure why it's failing npm test. This is passing on my local machine.

**Comment by maxwell-bland** [comment]
Missing dependency in package.json

**Comment by maxwell-bland** [comment]
There, just needed dependencies in package.json

**Pull request merged**
